-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."User"
(
    "UserName_PK" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Password" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Role" character varying(50) COLLATE pg_catalog."default" DEFAULT 'User'::character varying,
    "Location" text COLLATE pg_catalog."default",
    "VerificationStatus" boolean DEFAULT false,
    "CreatedAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "User_pkey" PRIMARY KEY ("UserName_PK"),
    CONSTRAINT "User_Email_key" UNIQUE ("Email")
);

CREATE TABLE IF NOT EXISTS public.equipment
(
    equipment_id serial NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    photo_url character varying(500) COLLATE pg_catalog."default",
    photo_binary character varying COLLATE pg_catalog."default",
    owner_username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    category character varying(100) COLLATE pg_catalog."default",
    daily_price numeric(10, 2) NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'available'::character varying,
    booked_till date,
    pickup_location character varying(255) COLLATE pg_catalog."default",
    rating_avg numeric(2, 1) DEFAULT 0.0,
    rating_count integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT equipment_pkey PRIMARY KEY (equipment_id)
);

CREATE TABLE IF NOT EXISTS public.report
(
    report_id serial NOT NULL,
    reporter_username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    report_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    subject character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying COLLATE pg_catalog."default",
    equipment_id integer,
    reservation_id integer,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'open'::character varying,
    priority character varying(20) COLLATE pg_catalog."default" DEFAULT 'medium'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT report_pkey PRIMARY KEY (report_id)
);

CREATE TABLE IF NOT EXISTS public.reservation
(
    reservation_id serial NOT NULL,
    equipment_id integer NOT NULL,
    owner_username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    reserver_username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::character varying,
    start_date date NOT NULL,
    end_date date NOT NULL,
    per_day_price numeric(10, 2) NOT NULL,
    total_price numeric(12, 2) NOT NULL,
    review_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reservation_pkey PRIMARY KEY (reservation_id)
);

CREATE TABLE IF NOT EXISTS public.review
(
    review_id serial NOT NULL,
    reservation_id integer NOT NULL,
    equipment_id integer NOT NULL,
    reviewer_username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    owner_username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    rating integer NOT NULL,
    comment text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT review_pkey PRIMARY KEY (review_id),
    CONSTRAINT uq_review_reservation UNIQUE (reservation_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    "UserName_PK" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Password" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Role" character varying(50) COLLATE pg_catalog."default" DEFAULT 'User'::character varying,
    "Location" character varying COLLATE pg_catalog."default",
    "VerificationStatus" boolean DEFAULT true,
    "CreatedAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY ("UserName_PK")
);

ALTER TABLE IF EXISTS public.equipment
    ADD CONSTRAINT equipment_owner_username_fkey FOREIGN KEY (owner_username)
    REFERENCES public."User" ("UserName_PK") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_equipment_owner_username
    ON public.equipment(owner_username);


ALTER TABLE IF EXISTS public.report
    ADD CONSTRAINT report_equipment_id_fkey FOREIGN KEY (equipment_id)
    REFERENCES public.equipment (equipment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.report
    ADD CONSTRAINT report_reporter_username_fkey FOREIGN KEY (reporter_username)
    REFERENCES public."User" ("UserName_PK") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_report_reporter_username
    ON public.report(reporter_username);


ALTER TABLE IF EXISTS public.report
    ADD CONSTRAINT report_reservation_id_fkey FOREIGN KEY (reservation_id)
    REFERENCES public.reservation (reservation_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.reservation
    ADD CONSTRAINT fk_reservation_equipment FOREIGN KEY (equipment_id)
    REFERENCES public.equipment (equipment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_reservation_equipment
    ON public.reservation(equipment_id);


ALTER TABLE IF EXISTS public.reservation
    ADD CONSTRAINT fk_reservation_owner FOREIGN KEY (owner_username)
    REFERENCES public."User" ("UserName_PK") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_reservation_owner
    ON public.reservation(owner_username);


ALTER TABLE IF EXISTS public.reservation
    ADD CONSTRAINT fk_reservation_reserver FOREIGN KEY (reserver_username)
    REFERENCES public."User" ("UserName_PK") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_reservation_reserver
    ON public.reservation(reserver_username);


ALTER TABLE IF EXISTS public.review
    ADD CONSTRAINT fk_review_equipment FOREIGN KEY (equipment_id)
    REFERENCES public.equipment (equipment_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_review_equipment
    ON public.review(equipment_id);


ALTER TABLE IF EXISTS public.review
    ADD CONSTRAINT fk_review_owner FOREIGN KEY (owner_username)
    REFERENCES public."User" ("UserName_PK") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_review_owner
    ON public.review(owner_username);


ALTER TABLE IF EXISTS public.review
    ADD CONSTRAINT fk_review_reservation FOREIGN KEY (reservation_id)
    REFERENCES public.reservation (reservation_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_review_reservation
    ON public.review(reservation_id);


ALTER TABLE IF EXISTS public.review
    ADD CONSTRAINT fk_review_reviewer FOREIGN KEY (reviewer_username)
    REFERENCES public."User" ("UserName_PK") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_review_reviewer
    ON public.review(reviewer_username);

END;